adil/accounts/urls.py
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static
from adil.accounts.views import SignUp
from adil.accounts.views import LoginView
from adil.accounts.views import LogoutView


urlpatterns = [
    re_path('^signup/$', SignUp.as_view(), name='signup'),
    re_path(r'^login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    re_path(r'^logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL + 'accounts/', document_root=settings.STATIC_ROOT)

adil/base/urls.py
import os
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static
from adil.base.views import HomeView


urlpatterns = [
    re_path('^$', HomeView.as_view(), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL + 'base/', document_root=settings.STATIC_ROOT)

adil/board/urls.py
import os
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from adil.board.views import CreateBoardView
from adil.board.views import ShowBoardsView
from adil.board.views import ListBoardsView


urlpatterns = [
    path('create/', CreateBoardView.as_view(), name='create'),
    path('show', ShowBoardsView.as_view(), name='show'),
    path('ajax/boards', ListBoardsView.as_view(), name='boards_list'),
]

if settings.DEBUG:
    static_folder = os.path.abspath(os.path.join(os.path.dirname(__file__), 'static', 'borad'))
    urlpatterns += static(settings.STATIC_URL + 'board/', document_root=static_folder)

adil/formation/urls.py
import os
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.urls import include
from django.conf import settings
from adil.base import views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('adil.base.urls', 'base'), namespace='base')),
    path('accounts/', include(('adil.accounts.urls', 'accounts'), namespace='accounts')),
    path('board/', include(('adil.board.urls', 'board'), namespace='board')),
    re_path(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
]

handler403 = views.handler403
handler404 = views.handler404
handler500 = views.handler500

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('500/', views.handler500),
        path('404/', views.handler404),
        path('403/', views.handler403),
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

adil/base/models.py
from django.db import models

adil/base/views.py
from django.views.defaults import page_not_found
from django.views.defaults import server_error
from django.views.defaults import permission_denied
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class HomeView(LoginRequiredMixin, TemplateView):
    """
    Class view to display dashboard
    """

    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        """
        Create context data from kwargs to be passed to template.
        :param kwargs: data to pass to template
        :return:
        """
        context = super().get_context_data(**kwargs)
        context['menu'] = {'home': {'is_active': True}}
        return context


def handler403(request):
    """
    custom 403 view
    :param request:
    :return:
    """
    return permission_denied(request, Exception(), template_name='base/403.html')


def handler404(request):
    """
    custom 404 view
    :param request:
    :return:
    """
    return page_not_found(request, Exception(), template_name='base/404.html')


def handler500(request):
    """
    Custom 500 view
    :param request:
    :return:
    """
    return server_error(request, template_name='base/500.html')

adil/base/templates/base/components/_css.html
{% load static %}

<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href={% static 'base/vendor/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css' %}>
<!-- Font Awesome -->
<link rel="stylesheet" href={% static 'base/vendor/AdminLTE/bower_components/font-awesome/css/font-awesome.min.css' %}>
<!-- Ionicons -->
<link rel="stylesheet" href={% static 'base/vendor/AdminLTE/bower_components/Ionicons/css/ionicons.min.css' %}>
<!-- Theme style -->
<link rel="stylesheet" href={% static 'base/vendor/AdminLTE/dist/css/AdminLTE.min.css' %}>
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href={% static 'base/vendor/AdminLTE/dist/css/skins/_all-skins.min.css' %}>

<link rel="stylesheet" href={% static 'base/css/aslm.css' %}>

adil/base/templates/base/components/_js.html
{% load static %}

<!-- jQuery 3 -->
<script src={% static 'base/vendor/AdminLTE/bower_components/jquery/dist/jquery.min.js' %}></script>
<!-- Bootstrap 3.3.7 -->
<script src={% static 'base/vendor/AdminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js' %}></script>
<!-- SlimScroll -->
<script src={% static 'base/vendor/AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}></script>
<!-- FastClick -->
<script src={% static 'base/vendor/AdminLTE/bower_components/fastclick/lib/fastclick.js' %}></script>
<!-- AdminLTE App -->
<script src={% static 'base/vendor/AdminLTE/dist/js/adminlte.min.js' %}></script>
<!-- AdminLTE for demo purposes -->
<script src={% static 'base/vendor/AdminLTE/dist/js/demo.js' %}></script>

adil/base/templates/base/components/breadcrumbs.html
<ol class="breadcrumb">
    {% for url, label in breadcrumbs %}
        <li>
            {% ifnotequal forloop.counter breadcrumbs_total %}
                <a href="{{ url }}">{{ label|safe }}</a>
            {% else %}
                <strong>{{ label|safe }}</strong>
            {% endifnotequal %}
        </li>
    {% endfor %}
</ol>

adil/base/templates/base/components/footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> {{ version }}
    </div>
    <strong>Copyright &copy; {% now 'Y' %}
        <a href="{% url 'base:home' %}">{{ manufacturer }}</a>.</strong> All rights reserved.
</footer>

adil/base/templates/base/components/menu.html
{% load static %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    {% if user.is_authenticated %}
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static 'base/img/user_man.png' %}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{ user.get_full_name }}</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> is Online</a>
                </div>
            </div>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="{% if menu.home.is_active %} active {% endif %}">
                    <a href="{% url 'base:home' %}">
                        <i class="fa fa-dashboard"></i> <span>Home</span>
                    </a>
                </li>
            </ul>
            <ul class="sidebar-menu" data-widget="tree">
                <li class="treeview {% if menu.board_show.is_active or  menu.board_create.is_active%} active {% endif %}">
                    <a href="{% url 'board:show' %}">
                        <i class="fa fa fa-bars"></i> <span>Board</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li {% if menu.board_show.is_active %} class="active" {% endif %}>
                            <a href="{% url 'board:show' %}"><i class="fa fa-eye"></i>Show</a></li>
                        <li {% if menu.board_create.is_active %} class="active" {% endif %}>
                            <a href="{% url 'board:create' %}"><i class="fa fa-plus-circle"></i>Create</a></li>
                    </ul>
                </li>
            </ul>
        </section>
    {% endif %}
    <!-- /.sidebar -->
</aside>

adil/base/templates/base/components/navbar.html
<header class="main-header">
    <!-- Logo -->
    <a href="{% url 'base:home' %}" class="logo">
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>{{ title }}</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                </li>
                <!-- Notifications: style can be found in dropdown.less -->
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                </li>
                <!-- Tasks: style can be found in dropdown.less -->
                <li class="dropdown user-menu">
                    <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                        <i class="fa fa-users"></i>
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'accounts:logout' %}">
                                    <i class="fa fa-sign-out"></i>
                                    Logout
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'accounts:login' %}">
                                    <i class="fa fa-sign-in"></i>
                                    Login
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:signup' %}">
                                    <i class="fa fa-user-plus"></i>
                                    Sign-Up
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

adil/base/templates/base/components/pagination.html
{%  load pagination %}

<ul class="pagination pagination-sm pull-right">
    {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
        <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for page_number in page_obj.paginator|page_range:page_obj.number %}
        {%if page_number%}
            {% if page_number == page_obj.number %}
                <li class="active"><span>{{ page_number }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
        {% else %}
             <li class="disabled"><a href="#">...</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>